# Generated by Django 3.1.2 on 2023-07-07 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Speisekarte', '0005_alter_gericht_options_alter_kategorie_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gericht',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='kategorie',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
